name: build

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "sektek/devcontainers"
          install: true
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./images/base
          platforms: linux/amd64,linux/arm64
          tags: "${{ vars.DOCKER_USER }}/devcontainer-base:latest"
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
      - name: Build and push (Elixir)
        uses: docker/build-push-action@v6
        with:
          context: ./images/elixir
          platforms: linux/amd64,linux/arm64
          tags: "${{ vars.DOCKER_USER }}/devcontainer-elixir:latest"
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
      - name: Build and push (Java)
        uses: docker/build-push-action@v6
        with:
          context: ./images/java
          platforms: linux/amd64,linux/arm64
          tags: "${{ vars.DOCKER_USER }}/devcontainer-java:latest"
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
